name: Release
on:
  create:
    tags:
      - v*
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Create release on GitHub
        run: "docker run --rm --privileged -e CGO_ENABLED=1 -e GITHUB_TOKEN=$GITHUB_TOKEN -e GOVERSION=$(go version | awk '{print $3;}') -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/go/src/nging -v /usr:/sysroot/usr -w /go/src/nging goreleaser/goreleaser-cross:v1.19.1 release --rm-dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
